services:
  simple-kimai-kiosk:
    container_name: my-nginx-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
